import Navbar from "./components/Navbar"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className='bg-[#FFF8EE] px-40 pt-12'>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
